//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int idDoctor { get; set; }
        public int idSpecialization { get; set; }
        public int idUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
