//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int idPrescription { get; set; }
        public int idMedicine { get; set; }
        public int idTreatment { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
