//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treatment()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int idTreatment { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateFinish { get; set; }
        public int idDoctor { get; set; }
        public int idUser { get; set; }
        public string observation { get; set; }
        public int idDiagnosis { get; set; }
    
        public virtual Diagnosi Diagnosi { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual User User { get; set; }
    }
}
